<div class="row">
    <div style="height: 500px;" class="col-md-7"></div>
    <div style="height: 500px;" class="col-md-5">
        <div class="panel panel-primary signup-panel">
            <div class="panel-heading">
                <h3 class="panel-title">Create account</h3>
            </div>
            <div class="panel-body">
                <form role="form" method="post" action="">
                    <div class="form-group">
                        <label for="inputUsername">Create username</label>
                        <input id="inputUsername" type="text" class="form-control" placeholder="Enter username">
                    </div>
                    <div class="form-group">
                        <label for="inputMobileNumber">Add mobile number</label>
                        <input id="inputMobileNumber" type="tel" class="form-control" placeholder="Enter mobile number">
                    </div>
                    <div class="form-group">
                        <label for="inputGender">Select gender</label>
                        <select id="inputMobileNumber"class="form-control" placeholder="Select your gender">
                            <option value="0">Female</option>
                            <option value="1">Male</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword">Create password</label>
                        <input id="inputPassword" type="password" class="form-control" placeholder="Type Password">
                    </div>
                    <div class="form-group">
                        <label for="inputRepeatPassword">Repeat password</label>
                        <input id="inputRepeatPassword" type="password" class="form-control" placeholder="Repeat password">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="slide-new-member">
    <div class="row">
        <div class="col-sm-6 col-md-3">
            <a href="#" class="thumbnail">
                <div class="image-crop">
                    <img style="width: 100%; display: block;" src="https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-ash3/1375740_10151967774423664_259933383_n.jpg">
                </div>
                <div class="caption">
                    <div class="member-contact color-primary"><b><?php echo $this->textHelper->character_limiter('cuterica +63093590****', 28, '&#8230;', false); ?></b></div>
                    <div class="member-short-msg">Hello to all add my no. to your phone</div>
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-md-3">
            <a href="#" class="thumbnail">
                <div class="image-crop">
                    <img style="width: 100%; display: block;" src="https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-frc3/1375725_10151921074891387_115492385_n.jpg">
                </div>
                <div class="caption">
                    <div class="member-contact color-primary"><b><?php echo $this->textHelper->character_limiter('cuterica +63093590****', 28, '&#8230;', false); ?></b></div>
                    <div class="member-short-msg "><?php echo $this->textHelper->character_limiter('I will rock your bed, so what are you waiting for lets do it. lets just have fun all day all night', 80); ?></div>
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-md-3">
            <a href="#" class="thumbnail">
                <div class="image-crop">
                    <img style="width: 100%; display: block;" src="https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-frc1/1385197_388606807935436_2096408593_n.jpg">
                </div>
                <div class="caption">
                    <div class="member-contact color-primary"><b><?php echo $this->textHelper->character_limiter('Charleen Rimolandya +63093456****', 28, '&#8230;', false); ?></b></div>
                    <div class="member-short-msg">Hello to all add my no. to your phone</div>
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-md-3">
            <a href="#" class="thumbnail">
                <div class="image-crop">
                    <img style="width: 100%; display: block;" src="https://fbcdn-sphotos-d-a.akamaihd.net/hphotos-ak-frc3/999051_655755061118524_1892436370_n.jpg">
                </div>
                <div class="caption">
                    <div class="member-contact color-primary"><b><?php echo $this->textHelper->character_limiter('cuterica +63093456****', 28, '&#8230;', false); ?></b></div>
                    <div class="member-short-msg">Hello to all add my no. to your phone</div>
                </div>
            </a>
        </div>
    </div>
</div>
